// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fourtynine.DataAccess;

#nullable disable

namespace fourtynine.DataAccess.Migrations
{
    [DbContext(typeof(DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("fourtynine.DataAccess.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("fourtynine.DataAccess.Picture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("PostingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PostingId");

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("fourtynine.DataAccess.Posting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Postings");
                });

            modelBuilder.Entity("fourtynine.DataAccess.Picture", b =>
                {
                    b.HasOne("fourtynine.DataAccess.Posting", "Posting")
                        .WithMany("Pictures")
                        .HasForeignKey("PostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posting");
                });

            modelBuilder.Entity("fourtynine.DataAccess.Posting", b =>
                {
                    b.HasOne("fourtynine.DataAccess.Author", "Author")
                        .WithMany("Postings")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("fourtynine.DataAccess.LocationPostingDetails", "Location", b1 =>
                        {
                            b1.Property<long>("PostingId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Address")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("PostingId");

                            b1.ToTable("Postings");

                            b1.WithOwner()
                                .HasForeignKey("PostingId");
                        });

                    b.OwnsOne("fourtynine.DataAccess.PricingPostingDetails", "Pricing", b1 =>
                        {
                            b1.Property<long>("PostingId")
                                .HasColumnType("bigint");

                            b1.Property<byte>("BargainKinds")
                                .HasColumnType("tinyint");

                            b1.Property<decimal?>("Price")
                                .HasColumnType("money");

                            b1.Property<decimal?>("PriceMax")
                                .HasColumnType("money");

                            b1.HasKey("PostingId");

                            b1.ToTable("Postings");

                            b1.WithOwner()
                                .HasForeignKey("PostingId");
                        });

                    b.OwnsOne("fourtynine.DataAccess.RealEstatePostingDetails", "RealEstate", b1 =>
                        {
                            b1.Property<long>("PostingId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Area")
                                .HasColumnType("decimal(8,1)");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("varchar(16)");

                            b1.Property<int>("Rooms")
                                .HasColumnType("int");

                            b1.Property<string>("SpacePurpose")
                                .IsRequired()
                                .HasColumnType("varchar(16)");

                            b1.HasKey("PostingId");

                            b1.ToTable("Postings");

                            b1.WithOwner()
                                .HasForeignKey("PostingId");
                        });

                    b.OwnsOne("fourtynine.DataAccess.VehiclePostingDetails", "Vehicle", b1 =>
                        {
                            b1.Property<long>("PostingId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Manufacturer")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<int>("Year")
                                .HasColumnType("int");

                            b1.HasKey("PostingId");

                            b1.ToTable("Postings");

                            b1.WithOwner()
                                .HasForeignKey("PostingId");
                        });

                    b.Navigation("Author");

                    b.Navigation("Location");

                    b.Navigation("Pricing");

                    b.Navigation("RealEstate");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("fourtynine.DataAccess.Author", b =>
                {
                    b.Navigation("Postings");
                });

            modelBuilder.Entity("fourtynine.DataAccess.Posting", b =>
                {
                    b.Navigation("Pictures");
                });
#pragma warning restore 612, 618
        }
    }
}
